#include "attacks.h"

vector<Attack> attacks = {
        Attack("Tackle", 40, 100, 1, PokemonType::Normal),
        Attack("Growl", 0, 100, 1, PokemonType::Normal),
        Attack("Thunderbolt", 90, 100, 26, PokemonType::Electric),
        Attack("Flamethrower", 90, 100, 39, PokemonType::Fire),
        Attack("Water Gun", 40, 100, 1, PokemonType::Water),
        Attack("Vine Whip", 45, 100, 13, PokemonType::Grass),
        Attack("Psybeam", 65, 100, 15, PokemonType::Psychic),
        Attack("Ice Beam", 90, 100, 37, PokemonType::Ice),
        Attack("Earthquake", 100, 100, 50, PokemonType::Ground),
        Attack("Rock Slide", 75, 90, 25, PokemonType::Rock),
        Attack("Confusion", 50, 100, 15, PokemonType::Psychic),
        Attack("Bite", 60, 100, 15, PokemonType::Dark),
        Attack("Double Kick", 30, 100, 12, PokemonType::Fighting),
        Attack("Quick Attack", 40, 100, 1, PokemonType::Normal),
        Attack("Hyper Beam", 150, 90, 50, PokemonType::Normal),
        Attack("Surf", 90, 100, 30, PokemonType::Water),
        Attack("Solar Beam", 120, 100, 43, PokemonType::Grass),
        Attack("Ember", 40, 100, 1, PokemonType::Fire),
        Attack("Smokescreen", 0, 100, 1, PokemonType::Normal),
        Attack("Fire Spin", 35, 85, 15, PokemonType::Fire),
        Attack("Barrage", 15, 85, 1, PokemonType::Normal),
        Attack("Mega Punch", 80, 85, 1, PokemonType::Normal),
        Attack("Mega Kick", 120, 75, 1, PokemonType::Normal),
        Attack("Seismic Toss", 0, 100, 1, PokemonType::Fighting),
        Attack("Strength", 80, 100, 1, PokemonType::Normal),
        Attack("Submission", 80, 80, 1, PokemonType::Fighting),
        Attack("Counter", 0, 100, 1, PokemonType::Fighting),
        Attack("Harden", 0, 100, 1, PokemonType::Normal),
        Attack("Absorb", 20, 100, 1, PokemonType::Grass),
        Attack("Mega Drain", 40, 100, 24, PokemonType::Grass),
        Attack("Leech Seed", 0, 90, 7, PokemonType::Grass),
        Attack("Growth", 0, 100, 15, PokemonType::Normal),
        Attack("Petal Dance", 120, 100, 31, PokemonType::Grass),
        Attack("Razor Leaf", 55, 95, 21, PokemonType::Grass),
        Attack("Poison Sting", 15, 100, 1, PokemonType::Poison),
        Attack("Acid", 40, 100, 1, PokemonType::Poison),
        Attack("Screech", 0, 85, 1, PokemonType::Normal),
        Attack("Fury Swipes", 18, 80, 1, PokemonType::Normal),
        Attack("Dynamic Punch", 100, 50, 1, PokemonType::Fighting),
        Attack("Mimic", 0, 100, 1, PokemonType::Normal),
        Attack("Night Shade", 0, 100, 1, PokemonType::Ghost),
        Attack("Confuse Ray", 0, 100, 1, PokemonType::Ghost),
        Attack("Dream Eater", 100, 100, 1, PokemonType::Psychic),
        Attack("Rage", 20, 100, 1, PokemonType::Normal),
        Attack("Teleport", 0, 100, 1, PokemonType::Psychic),
        Attack("Self-Destruct", 200, 100, 1, PokemonType::Normal),
        Attack("Explosion", 250, 100, 1, PokemonType::Normal),
        Attack("Lick", 30, 100, 1, PokemonType::Ghost),
        Attack("Hydro Pump", 110, 80, 43, PokemonType::Water),
        Attack("Whirlpool", 35, 85, 15, PokemonType::Water),
        Attack("Hydro Cannon", 150, 90, 50, PokemonType::Water)
};